curriculo/urls.py
from django.urls import path

from .views import curso, disciplina

app_name = 'curriculo'
urlpatterns = [
    path('<str:sigla>/', curso, name='curso'),
    path('<str:sigla>/disciplina/<str:identificador>/', disciplina, name="disciplina")
]

lms/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import error404

urlpatterns = [
    path("", include("core.urls")),
    path("cursos/", include('curriculo.urls')),
    path('restrito/', include('restrito.urls')),
    path('admin/', admin.site.urls, name="admin"),
]

handler404 = error404

curriculo/models/atividade.py
from django.db import models

class Atividade(models.Model):
    titulo = models.TextField(max_length=255, unique=True)
    descricao = models.TextField(max_length=255)
    conteudo = models.TextField(max_length=255)
    tipo = models.TextField(max_length=255)
    extras = models.TextField(max_length=255)
    professor = models.ForeignKey("contas.Professor", on_delete=models.PROTECT)
    class Meta():
        db_table="Atividade"

class AtividadeVinculada(models.Model):
    status = models.IntegerField()
    rotulo = models.TextField(max_length=255)
    atividade = models.ForeignKey(Atividade, on_delete=models.PROTECT)
    professor = models.ForeignKey("contas.Professor", on_delete=models.PROTECT)
    disciplina_ofertada = models.ForeignKey("curriculo.DisciplinaOfertada", on_delete=models.PROTECT)
    class Meta():
        db_table="AtividadeVinculada"
class EntregaAtividade(models.Model):
    titulo = models.TextField(max_length=100)
    resposta = models.TextField(max_length=255)
    dt_entrega = models.DateField()
    status = models.IntegerField()
    nota = models.IntegerField()
    dt_avaliacao = models.DateField()
    obs = models.TextField(max_length=255)
    aluno = models.ForeignKey("contas.Aluno", on_delete=models.PROTECT)
    atividade_vinculada = models.ForeignKey("curriculo.AtividadeVinculada", on_delete=models.PROTECT)
    professor = models.ForeignKey("contas.Professor", on_delete=models.PROTECT)
    class Meta():
        db_table="EntregaAtividade"
class Mensagem(models.Model):
    assunto = models.TextField(max_length=255)
    referencia = models.TextField(max_length=255)
    conteudo = models.TextField(max_length=255)
    status = models.IntegerField()
    dt_envio = models.DateField()
    dr_resposta = models.DateField()
    resposta = models.TextField(max_length=1000)
    aluno = models.ForeignKey("contas.Aluno", on_delete=models.PROTECT)
    professor = models.ForeignKey("contas.Professor", on_delete=models.PROTECT)
    class Meta():
        db_table="Mensagem"    

curriculo/models/curso.py
from django.db import models

TIPOS_CURSOS = (
    ('T', 'Tecnólogo'),
    ('G', 'Graduação')
)

class Curso(models.Model):

    nome = models.CharField('Nome', max_length=120)

    sigla = models.CharField('Sigla', max_length=5, unique=True)

    sobre = models.TextField('Sobre o curso', null=True)

    duracao = models.SmallIntegerField('Semestres')

    tipo = models.CharField('Tipo', max_length=1, choices=TIPOS_CURSOS)

    noturno = models.BooleanField('Noturno?')

    diurno = models.BooleanField('Diurno?')

    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'CURSO'

curriculo/models/disciplina.py
from django.db import models

STATUS = (
    ('ABERTO','Aberta'),
    ('FECHADO', 'Fechada')
)

class Disciplina(models.Model):

    nome = models.CharField(
        'Nome',
        max_length=30,
        unique=True
    )

    identificador = models.CharField(
        'Identificador',
        max_length=30,
        unique=True
    )

    data = models.DateField(
        "Data de Início",
        auto_now_add=True
    )

    status = models.CharField(
        "Status",
        max_length=10,
        choices=STATUS
    )

    carga_horaria = models.SmallIntegerField(
        "Carga Horária"
    )

    percentual_pratico = models.SmallIntegerField(
        "Percentual Prático"
    )

    percentual_teorico = models.SmallIntegerField(
        "Percentual Teórico"
    )

    plano_de_ensino = models.TextField(
        "Plano de Ensino",
        blank=True
    )

    competencias = models.TextField(
        "Competências",
        blank=True
    )

    habilidades = models.TextField(
        "Habilidades",
        blank=True
    )
    
    ementa = models.TextField(
        "Ementa",
        blank=True
    )

    conteudo_programatico = models.TextField(
        "Conteúdo Programático",
        blank=True
    )

    bibliografia_basica = models.TextField(
        "Bibliografia Básica",
        blank=True
    )

    bibliografia_complementar = models.TextField(
        "Bibliografia Complementar",
        blank=True
    )

    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'DISCIPLINA'

class SolicitacaoMatricula(models.Model):

    nome = models.CharField(
        'Nome',
        max_length=30,
        unique=True
    )

    identificador = models.CharField(
        'Identificador',
        max_length=30,
        unique=True
    )

    data = models.DateField(
        "Data de Início",
        auto_now_add=True
    )

    status = models.CharField(
        "Status",
        max_length=10,
        choices=STATUS
    )

    carga_horaria = models.SmallIntegerField(
        "Carga Horária"
    )

    percentual_pratico = models.SmallIntegerField(
        "Percentual Prático"
    )

    percentual_teorico = models.SmallIntegerField(
        "Percentual Teórico"
    )

    plano_de_ensino = models.TextField(
        "Plano de Ensino",
        blank=True
    )

    competencias = models.TextField(
        "Competências",
        blank=True
    )

    habilidades = models.TextField(
        "Habilidades",
        blank=True
    )
    
    ementa = models.TextField(
        "Ementa",
        blank=True
    )

    conteudo_programatico = models.TextField(
        "Conteúdo Programático",
        blank=True
    )

    bibliografia_basica = models.TextField(
        "Bibliografia Básica",
        blank=True
    )

    bibliografia_complementar = models.TextField(
        "Bibliografia Complementar",
        blank=True
    )

    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'Solicitacao_Matricula'

class DisciplinaOfertada(models.Model):
    dt_inicio = models.DateField()
    dt_fim = models.DateField()
    ano = models.IntegerField()
    semestre = models.IntegerField()
    turma = models.CharField(max_length=1)
    metodologia = models.TextField(max_length=255)
    recursos = models.TextField(max_length=255)
    criterio_avaliacao = models.TextField(max_length=1000)
    plano_aula = models.TextField(max_length=1000)
    disciplina = models.ForeignKey("curriculo.Disciplina", on_delete=models.PROTECT)
    professor = models.ForeignKey("contas.Professor", on_delete=models.PROTECT)
    coordenador = models.ForeignKey("contas.Coordenador", on_delete=models.PROTECT)
    curso = models.ForeignKey("curriculo.Curso", on_delete=models.PROTECT)

    class Meta:
        unique_together = ('curso', 'disciplina', 'turma', 'ano', 'semestre')
        db_table = 'DISCIPLINA_OFERTADA'

curriculo/views.py
from datetime import datetime

from django.shortcuts import render, get_object_or_404

from .models import Curso, DisciplinaOfertada

# Create your views here.
def curso(request, sigla):
    curso = get_object_or_404(Curso, sigla=sigla)

    curso.semestres = range(1, curso.duracao+1)

    hoje = datetime.now()
    ano = hoje.year
    semestre = 1 if hoje.month <=6 else 2    
    disciplinas = DisciplinaOfertada.objects.filter(ano=ano, semestre=semestre, curso=curso).order_by("semestre")
    
    context = {
        'curso': curso,
        'disciplinas': disciplinas
    }
    return render(request, 'curriculo/curso.html', context)

def disciplina(request, sigla, identificador):
    disciplina = {
        'nome': 'Tecnologias Web',
        'carga': '80 Horas',
        'descricao': 'Conceitos e fundamentos: Internet, Intranet e Extranet. Arquitetura Cliente-Servidor. Desenvolvimento de aplicações WEB Padrões Web. HTML (HyperText Markup Language) e CSS ( Cascading Style Sheets). Sintaxe, comandos JavaScript e integração com HTML. Noções de NodeJS. Python e Framework de Desenvolvimento.  Arquitetura Model-View-Controller; a camada de acesso a banco de dados; Padrão de endereçamento http; aspetos de segurança, componentização JQuery + AJAX.',
        'professor': 'Prof Yuri Dirickson'
    }
    context = {
        'disciplina':disciplina
    }
    return render(request, 'curriculo/disciplina.html', context)

curriculo/templates/curriculo/curso.html
{% extends "base.html" %}
{% load static %}
{% block titulo %}
    {{ curso.nome }}
{% endblock  %}

{% block links %}
<link rel="stylesheet" href="{% static 'css/curso.css' %}">
{% endblock %}

{% block main %}
    <section class="container d-flex flex-wrap justify-content-between">
        <h1 class="text-center w-100">{{ curso.nome }}</h1>

        <section class="sobre border bg-light border-primary mx-2 p-3">
            <h2>Sobre o Curso</h2>
            {{ curso.sobre | linebreaks }}
        </section>
        <section class="informacoes mx-2">
            <h2>Informações</h2>

            <h3>{{ curso.get_tipo_display }}</h3>

            <p><span class="font-weight-bold text-primary">Período:</span></p>

            <ul class="list-group">
                {% if curso.diurno %}<li class="list-group-item"><span class="font-weight-bold text-primary">Matutino</span> | 08h00 às 11h40 |</li>{% endif %}
                {% if curso.noturno %}<li class="list-group-item"><span class="font-weight-bold text-primary">Noturno</span> | 19h00 às 23h40 |</li>{% endif %}
            </ul>

            <p><span class="font-weight-bold text-primary">Duração:</span> {{ curso.duracao }} semestres</p>

        </section>
        <section class="curriculo w-100 text-center my-2">
            <h2>Matriz Curricular</h2>
            <div class="row">
                <div class="col-3">
                    <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                        {% for semestre in curso.semestres %}
                            <a class="nav-link {% if forloop.first %}active{% endif %}" id="v-pills-{{ semestre }}-tab" data-toggle="pill" href="#v-pills-{{ semestre }}" role="tab" aria-controls="v-pills-{{ semestre }}" aria-selected="{% if forloop.first %}true{% else %}false{% endif %}">{{ semestre }}º Semestre</a>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-9">
                    <div class="tab-content" id="v-pills-tabContent">
                        {% for ofertas in curso.disciplinas %}
                            <div class="tab-pane fade {% if forloop.first %}show active{% endif %}" id="v-pills-{{ forloop.counter }}" role="tabpanel" aria-labelledby="v-pills-{{ forloop.counter }}-tab">
                                <div class="list-group">
                                    {% for disciplina in semestre %}
                                       <a href="{% url 'curriculo:disciplina' curso.sigla disciplina.nome|slugify %}" class="list-group-item list-group-item-action">{{ disciplina.nome }}: {{ disciplina.carga }}</a>
                                    {% endfor %}
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock  %}

curriculo/templates/curriculo/disciplina.html
{% extends 'base.html' %}

{% block titulo %}
    {{ disciplina.nome }}
{% endblock  %}

{% block main %}
    <h1 class="text-center">{{ disciplina.nome }}</h1>
{% endblock %}