core/urls.py
from django.urls import path

from .views import index, contato, entrar, sair

app_name = "core"

urlpatterns = [
    path("", index, name="home"),
    path('contato/', contato, name="contato"),
    path('entrar/', entrar, name="login"),
    path('sair/', sair, name="logout")
]

curriculo/urls.py
from django.urls import path

from .views import curso, disciplina

app_name = 'curriculo'
urlpatterns = [
    path('<str:sigla>/', curso, name='curso'),
    path('<str:sigla>/disciplina/<str:identificador>/', disciplina, name="disciplina")
]

lms/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import error404

urlpatterns = [
    path("", include("core.urls")),
    path("cursos/", include('curriculo.urls')),
    path('restrito/', include('restrito.urls')),
    path('admin/', admin.site.urls, name="admin"),
]

handler404 = error404

restrito/urls.py
from django.urls import path

from .views import home_professor

app_name = 'restrito'
urlpatterns = [
    path('professor/', home_professor, name="home_professor")
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms

from django.core.mail import send_mail

ASSUNTOS = (
    ('', ' - Selecione '),
    ('B', 'Bug'),
    ('R', 'Reclamação'),
    ('S', 'Sugestão')
)

class ContatoForm(forms.Form):

    email = forms.EmailField(
        label='E-Mail'
    )

    nome = forms.CharField(
        label='Nome Completo'
    )

    assunto = forms.ChoiceField(
        label='Assunto',
        choices=ASSUNTOS
    )

    mensagem = forms.CharField(
        label='Mensagem',
        widget=forms.Textarea
    )

    def is_valid(self):
        valido = super(ContatoForm, self).is_valid()

        if valido:
            assunto = ''
            for tupla in ASSUNTOS:
                if tupla[0] == self.cleaned_data['assunto']:
                    assunto = tupla[1]
                    break

            send_mail(
                'Mensagem do Site - Assunto: '+assunto,
                self.cleaned_data['mensagem'],
                self.cleaned_data['email'],
                ['contato@impacta.com.br']
            )

        return valido

core/views.py
from datetime import datetime

from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.contrib import messages

from .forms import ContatoForm

# Create your views here.
def index(request):
    return render(request, "index.html")

def contato(request):
    context = {}
    if request.POST:
        form = ContatoForm(request.POST)
        if form.is_valid():
            messages.success(request, 'Sua mensagem foi enviada com sucesso') 
        else:
            messages.error(request, 'Problemas ao enviar seu e-mail!')
    else:
        form = ContatoForm()

    context["form"] = form
    return render(request, 'contato.html', context)

def error404(request, exception=None):
    return render(request, 'error/404.html')

def sair(request):
    logout(request)
    return redirect('core:home')

def entrar(request):
    context = {}
    if request.POST:
        usuario = request.POST.get('username')
        senha = request.POST.get('password')
        usuario = authenticate(username=usuario, password=senha)
        if usuario:
            login(request, usuario)
            return redirect('restrito:home_professor')
        else:
            messages.error(request, 'Usuário ou senha incorretos!')
    return render(request, 'entrar.html', context)

core/templates/base.html
{% load static %}

<!doctype html>
<html lang="pt-br">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="LMS Example for Impacta">
  <meta name="author" content="Yuri Dirickson">
  <link rel="icon" href="{% static 'favicon.ico' %}">

  <title>{% block titulo %}{% endblock %}</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz"
    crossorigin="anonymous">
  <link href="{% static 'css/site.css' %}" rel="stylesheet">
  {% block links %}{% endblock %}
</head>

<body>

  <header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand text-hide" href="{% url 'core:home' %}">
        <img src="{% static 'imagens/impacta-logo.png' %}" alt="logo da Impacta" />
        LMS IMPACTA
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              Cursos
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for curso in cursos_menu %}
                <a class="dropdown-item" href="{% url 'curriculo:curso' curso.sigla %}">{{ curso.sigla }}</a>
              {% empty %}
                <p class="p-3 text-muted">
                  Erro ao recuperar cursos
                </p>
              {% endfor %}
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:contato' %}">Contato</a>
          </li>
        </ul>
          <ul class="navbar-nav">
            {% if not user.is_authenticated %}
            <li class="nav-item">
                <div class="btn-group" role="group">
                  <a class="btn btn-outline-primary" href="{% url 'core:login' %}">Entrar</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                  aria-haspopup="true" aria-expanded="false">
                  <img src="{% static 'imagens/profile.png' %}" class="avatar" alt="foto do usuário" />
                  Olá {{ user }}
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  {% if user.tipo == 'C'  %}
                    <a class="dropdown-item" href="#">Área do Coordenador</a>
                  {% elif user.tipo == 'P' %}
                    <a class="dropdown-item" href="{% url 'restrito:home_professor'  %}">Área do Professor</a>
                  {% else %}
                    <a class="dropdown-item" href="#">Área do Aluno</a>
                  {% endif %}
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'core:logout' %}">Sair</a>
                </div>
            </li>
            {% endif %}
        </ul>
      </div>
    </nav>
  </header>

  <main role="main">
    {% if messages %}
      {% for message in messages %}
        <div role="alert" class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %}">
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}
    
    {% block main %}

    {% endblock %}

    <!-- FOOTER -->
    <footer class="text-white bg-secondary mt-3 py-3 px-2">
      <p class="float-right"><a href="#">Topo</a></p>
      <p class="text-center">{% now 'Y' %} Faculdade Impacta 11 3254-8300 Todos os direitos reservados.</p>
    </footer>
  </main>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
</body>

</html>

core/templates/contato.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block titulo %}
Contato
{% endblock titulo %}

{% block main %}
<form method="POST" novalidate>
    {% csrf_token %}
    <h1>Entre em contato conosco!</h1>
    {% include "forms/form-group.html" with form=form %}
    
    <button type="submit" class="btn btn-primary mb-2">Enviar</button>
</form>
{% endblock %}

core/templates/entrar.html
{% extends "base.html" %}

{% block titulo %}
    Entrar
{% endblock %}

{% block main %}
    <form method="POST">
        <h1>Entrar</h1>
        {% csrf_token %}
        <div class="form-group">
            <label for="entrar-usuario">Usuário</label>
            <input type="text" class="form-control" id="entrar-usuario" name="username" required />
        </div>
        <div class="form-group">
            <label for="entrar-senha">Senha</label>
            <input type="password" class="form-control" id="entrar-senha" name="password" required/>
        </div>
        <button type="submit" class="btn btn-primary">Entrar</button>
    </form>
{% endblock %}

core/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block titulo %}
  Home
{% endblock %}

{% block links %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block main %}
  <div class="jumbotron">
    <h1 class="display-4">Vestibular para {{semestre}}º de {{ ano }} </h1>
    <p class="lead">Faça já a sua inscrição e garanta o seu futuro.</p>
    <a class="btn btn-primary btn-lg" href="#" role="button">Inscreva-se Já</a>
  </div>
  <div class="container marketing">
    <h1>Prêmios e Reconhecimentos</h1>
    <!-- Three columns of text below the carousel -->
    <div class="card-deck justify-content-around">
      <article class="card text-center bg-dark text-white p-2">
        <img class="card-img-top premio" src="{% static 'imagens/premios/enade-ADM.png' %}" alt="Card image cap">
        <h5 class="card-title">Top 10 ENADE/MEC SP</h5>
        <h6 class="card-subtitle mb-2 text-primary font-weight-bold">Graduação em Administração</h6>
        <p class="card-text">
            Nota 4 na avaliação do MEC – 10.ª maior nota entre as faculdades privadas da cidade de São Paulo.
          </p>
          <p class="card-text"></p>
            3 estrelas na avaliação realizada pelo Guia do Estudante, da Editora Abril, que seleciona os melhores cursos para os estudantes que estão se preparando para o vestibular.
          </p> 
          <p class="card-text"></p>
            Destaque no portal da Revista Exame como o curso que está entre os melhores do Brasil. (06/2017)
        </p>
        <p><a class="btn btn-primary" href="#" role="button">Confira mais sobre o curso</a></p>
      </article><!-- /.col-lg-4 -->
      <article class="card text-center bg-dark text-white p-2">
          <img class="card-img-top premio" src="{% static 'imagens/premios/enade-ADS.png' %}" alt="Card image cap">
          <h5 class="card-title">Maior Nota ENADE SP</h5>
          <h6 class="card-subtitle mb-2 text-primary font-weight-bold">Graduação em Análise e Desenvolvimento de Sistemas</h6>
          <p class="card-text">Nota 4 na avaliação do ENADE/MEC - 1.º melhor curso da cidade de São Paulo.</p>
          <p><a class="btn btn-primary" href="#" role="button">Confira mais sobre o curso</a></p>
      </article><!-- /.col-lg-4 -->
      <article class="card text-center bg-dark text-white p-2">
          <img class="card-img-top premio" src="{% static 'imagens/premios/enade-RD.png' %}" alt="Card image cap">
          <h5 class="card-title">Top 4 ENADE/MEC SP</h5>
          <h6 class="card-subtitle mb-2 text-primary font-weight-bold">Graduação em Redes de Computadores</h6>
          <p class="card-text">Nota 3 na avaliação do ENADE/MEC - 4.º melhor curso da cidade de São Paulo.</p>
        <p><a class="btn btn-primary" href="#" role="button">Confira mais sobre o curso</a></p>
      </article><!-- /.col-lg-4 -->
      <article class="card text-center bg-dark text-white p-2">
          <img class="card-img-top premio" src="{% static 'imagens/premios/enade-SI.png' %}" alt="Card image cap">
          <h5 class="card-title">Top 3 ENADE/MEC SP</h5>
          <h6 class="card-subtitle mb-2 text-primary font-weight-bold">Graduação em Sistemas da Informação</h6>
          <p class="card-text">Nota 4 na avaliação do ENADE/MEC - 3.º melhor curso da cidade de São Paulo.</p>
        <p><a class="btn btn-primary" href="#" role="button">Confira mais sobre o curso</a></p>
      </article><!-- /.col-lg-4 -->
    </div><!-- /.row -->

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">Conheça o Smartclass</h2>
        <p class="lead">As salas de aula da Faculdade Impacta são equipadas com lousas eletrônicas, que capturam
          todos os pontos das aulas <strong>presenciais</strong>, como voz, escrita <strong>dinâmica</strong>,
          vídeos e navegação do professor. Todo o conteúdo é gravado e disponibilizado em uma sala de ensino
          virtual para que o aluno assista quando e onde quiser, de qualquer plataforma digital.</p>
      </div>
      <div class="col-md-5">
        <img class="featurette-image img-fluid mx-auto" 
        src="{% static 'imagens/play-smartclass.jpg' %}" alt="play do smartclass">
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
        <h2 class="featurette-heading">Impacta Empreenda 360 Graus</span></h2>
        <p class="lead">
            Por meio da OPE – Oficina Projeto Empresa, que é realizada durante o curso, o aluno tem a oportunidade de construir sua própria startup. O programa de incentivo ao empreendedorismo tem o apoio de grandes nomes do mercado, como a FIESP.
        </p>
        <p class="lead">
            Alguns cases de sucesso já foram realizados por alunos Impacta, como o Projeto “Desperta Saúde” – Universidade São Camilo e Centro Cyber Segurança Impacta.
        </p>
    </div>

    <hr class="featurette-divider">

  </div>
{% endblock %}